// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace HousingIntel
{
    public partial class HouseIntelML
    {
        /// <summary>
        /// model input class for HouseIntelML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [ColumnName(@"MSSubClass")]
            public float MSSubClass { get; set; }

            [ColumnName(@"MSZoning")]
            public string MSZoning { get; set; }

            [ColumnName(@"LotArea")]
            public float LotArea { get; set; }

            [ColumnName(@"LotConfig")]
            public string LotConfig { get; set; }

            [ColumnName(@"BldgType")]
            public string BldgType { get; set; }

            [ColumnName(@"OverallCond")]
            public float OverallCond { get; set; }

            [ColumnName(@"YearBuilt")]
            public float YearBuilt { get; set; }

            [ColumnName(@"YearRemodAdd")]
            public float YearRemodAdd { get; set; }

            [ColumnName(@"Exterior1st")]
            public string Exterior1st { get; set; }

            [ColumnName(@"BsmtFinSF2")]
            public float BsmtFinSF2 { get; set; }

            [ColumnName(@"TotalBsmtSF")]
            public float TotalBsmtSF { get; set; }

            [ColumnName(@"SalePrice")]
            public float SalePrice { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for HouseIntelML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [ColumnName(@"MSSubClass")]
            public float MSSubClass { get; set; }

            [ColumnName(@"MSZoning")]
            public float[] MSZoning { get; set; }

            [ColumnName(@"LotArea")]
            public float LotArea { get; set; }

            [ColumnName(@"LotConfig")]
            public float[] LotConfig { get; set; }

            [ColumnName(@"BldgType")]
            public float[] BldgType { get; set; }

            [ColumnName(@"OverallCond")]
            public float OverallCond { get; set; }

            [ColumnName(@"YearBuilt")]
            public float YearBuilt { get; set; }

            [ColumnName(@"YearRemodAdd")]
            public float YearRemodAdd { get; set; }

            [ColumnName(@"Exterior1st")]
            public float[] Exterior1st { get; set; }

            [ColumnName(@"BsmtFinSF2")]
            public float BsmtFinSF2 { get; set; }

            [ColumnName(@"TotalBsmtSF")]
            public float TotalBsmtSF { get; set; }

            [ColumnName(@"SalePrice")]
            public float SalePrice { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("HouseIntelML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
